[patch.crates-io.face_bridge]
path = "/home/ubuntu/neuro_bot_ws/install/face_bridge/share/face_bridge/rust"

[patch.crates-io.brain_core]
path = "/home/ubuntu/neuro_bot_ws/install/brain_core/share/brain_core/rust"
